In [1]:
import numpy as np

**Arrays**

In [3]:
a = np.array([1,4,5,8], float)

In [4]:
a

array([ 1.,  4.,  5.,  8.])

In [5]:
type(a)

numpy.ndarray

Arrays are accessed just like lists so they can be sliced and manipulated just like lists:

In [6]:
a[:2]

array([ 1.,  4.])

In [7]:
a[3]

8.0

In [8]:
a[0] = 5
a

array([ 5.,  4.,  5.,  8.])

Multidimensional arrays can, unlike lists, be accessed using commas inside a bracket notation. So here is an example with a two dimensional array, i.e, a matrix: 

In [10]:
a = np.array([[1,2,3], [4,5,6]], float)

In [11]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [12]:
a[0,0]

1.0

In [13]:
a[0,1]

2.0

A single ":" inside a dimension means using everything in that dimension. 

In [14]:
a[1,:]

array([ 4.,  5.,  6.])

In [15]:
a[:,2]

array([ 3.,  6.])

Get the second column: 

In [16]:
a[:,1]

array([ 2.,  5.])

In [17]:
a[-1:,-2:]

array([[ 5.,  6.]])

In [18]:
a[-1:]

array([[ 4.,  5.,  6.]])

In [19]:
a[-2:]

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [20]:
a[-2:,-1]

array([ 3.,  6.])

In [21]:
a[-2:,-2]

array([ 2.,  5.])

In [22]:
a.shape

(2, 3)

In [23]:
a.dtype

dtype('float64')

In [24]:
len(a)

2

Note that len() returns the length of the first axis, so in this case the number of rows. 

In [25]:
2 in a

True

In [26]:
0 in a

False

Arrays can be shaped by tuples that specify new dimensions. So in the next example we turn a ten-element one-dimensional array into a two-dimensional array whose first axis has five elements and whose second axis has two elements: 

In [28]:
a = np.array(range(10), float)

In [29]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [32]:
a = a.reshape((5,2))

In [33]:
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

So, using the .reshape method on an np array in the two dimensional case, the first number refers to the number of rows and the second to the number of columns. 

Also, note that reshape does not alter the original array. (what does it do then?)

The name-binding approach of Python holds in numpy. The copy function makes a new copy of an array in memory, not merely another pointer to the same object. 

In [34]:
a = np.array([1,2,3], float)
b = a
c = a.copy()
a

array([ 1.,  2.,  3.])

In [35]:
a[0] = 0

In [36]:
a

array([ 0.,  2.,  3.])

In [37]:
b

array([ 0.,  2.,  3.])

In [38]:
c

array([ 1.,  2.,  3.])

You can create a list from an array.

In [39]:
a = np.array([1,2,3], float)
a.tolist()

[1.0, 2.0, 3.0]

In [40]:
list(a)

[1.0, 2.0, 3.0]

In [41]:
a

array([ 1.,  2.,  3.])

You can convert the raw data in an array to a binary string(i.e., not in human-readable form) using hte tostring function. The fromstring function then allows an array to be created from this data later on. These routines are sometimes convenient for saving large amounts of array data in files that can be read later on: 

In [46]:
a = np.array([1,2,3], float)
s = a.tostring()
s

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [47]:
np.fromstring(s)

array([ 1.,  2.,  3.])

In [48]:
a.fill(0)

In [49]:
a

array([ 0.,  0.,  0.])

Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched.

In [51]:
a = np.array(range(6), float).reshape((2,3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [52]:
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

The flatten method will create a one dimensional array:

In [53]:
a.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.])

You can concatenate with the concatenate method. You get a tuple of the arrays to be joined. 

In [54]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a,b,c))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [55]:
np.concatenate((a,b,c), axis=0)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

And you can increase the dimensionality of the array by using the newaxis constant in bracket notation.

In [57]:
a = np.array([1,2,3], float)
a

array([ 1.,  2.,  3.])

In [58]:
a[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

In [59]:
a[:, np.newaxis].shape

(3, 1)

**Other Ways to Create Arrays**

The arange() function is similar to the range() function but returns an array. 

In [60]:
np.arange(5, dtype=float)

array([ 0.,  1.,  2.,  3.,  4.])

In [61]:
np.arange(1,6,2, dtype=int)

array([1, 3, 5])

zeros and ones are functions, too. They fill the specified dimensions with those values. 

In [62]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [63]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

And there is a zeros_like and ones_like function that creates new arrays with the same dimensions and type as the existing array supplied as an argument to the respective functions. 

In [65]:
a = np.ones((2,3), dtype=float)

In [66]:
np.zeros_like(a)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [67]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [68]:
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

The eye function returns the matrix wiht ones along the ith diagonal.

In [69]:
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

**Array Mathematics**

So arrays have to be the same size to do addition with matrixes. 

In [70]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

array([ 6.,  4.,  9.])

In [71]:
a - b

array([-4.,  0., -3.])

In [72]:
a * b

array([  5.,   4.,  18.])

In [73]:
b / a

array([ 5.,  1.,  2.])

In [74]:
a % b

array([ 1.,  0.,  3.])

In [75]:
7 % 10

7

In [76]:
b**a

array([   5.,    4.,  216.])

Usually, when you have arrays that don't match in size and you try to perform math on them you get an error. But Python can also 'broadcast' arrays so that the smaller array will be increased to the necessary size to perform the operation. 

In [77]:
a = np.array ([[1,2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [78]:
b

array([-1.,  3.])

In [79]:
a + b

array([[ 0.,  5.],
       [ 2.,  7.],
       [ 4.,  9.]])

If it is ambiguous how to broadcast the arrays to make the specified operations possible we can specify the way we want to broadcast with newaxis.

In [80]:
a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [81]:
b

array([-1.,  3.])

In [82]:
a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [83]:
a + b[np.newaxis, :]

array([[-1.,  3.],
       [-1.,  3.]])

In [85]:
a + b[:, np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

There are lost of other functions that you can call, like, abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, and arctanh. 

In [86]:
a = np.array([1,4, 9], float)

In [87]:
np.sqrt(a)

array([ 1.,  2.,  3.])

The functions floor, ceil and rint give the lower, upper and nearest (rounded) integer:

In [88]:
a = np.array([1.1, 1.5, 1.9], float)

In [89]:
np.floor(a)

array([ 1.,  1.,  1.])

In [90]:
np.ceil(a)

array([ 2.,  2.,  2.])

In [91]:
np.rint(a)

array([ 1.,  2.,  2.])

Some important constants:

In [92]:
np.pi

3.141592653589793

In [93]:
np.e

2.718281828459045

**Array Iteration**

You can iterate over arrays in a way that is similar to the way you can iterate over lists.

In [94]:
a = np.array([1,4,5], int)

In [95]:
for x in a: 
    print x

1
4
5


For multidimensional arrays the iteration proceeds over the first axis such that each loop returns a subsection of the array: 

In [96]:
a = np.array([[1,2], [3,4], [5,6]], float)
for x in a: 
    print x

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


In [97]:
for (x, y) in a:
    print x*y

2.0
12.0
30.0


**Basic Array Operations**

In [98]:
a = np.array([2,4,3], float)
a.sum()

9.0

In [99]:
a.prod()

24.0

In [100]:
a.mean()

3.0

In [101]:
a.var()

0.66666666666666663

In [102]:
a.std()

0.81649658092772603

In [103]:
a.min()

2.0

In [104]:
a.max()

4.0

The argmin and argmax functions return the array indices of the minimum and maximum values. 

In [105]:
a.argmin()

0

In [106]:
a.argmax()

1

In [107]:
a = np.array([6,2,5,-1,0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [108]:
a.sort()

In [109]:
a

array([-1.,  0.,  2.,  5.,  6.])

In [110]:
a = np.array([[0,2], [3, -1], [3, 5]], float)

In [111]:
a.mean(axis=0)

array([ 2.,  2.])

In [112]:
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [113]:
a.mean(axis=1)

array([ 1.,  1.,  4.])

Seems to behave the opposite of the way I expected. So axis=0 means add a new row of values with the mean of each column and axis=1 means create a new columns of the means of each row. Kinda makes sense.

In [114]:
np.unique(a)

array([-1.,  0.,  2.,  3.,  5.])

Takes out the three that is repeated. You can also extract the diagonal.

In [115]:
a.diagonal()

array([ 0., -1.])

**Comparision operators and value testing**

In [116]:
a = np.array([1,3,0], float)
b = np.array([0,3,2], float)

In [117]:
a>b

array([ True, False, False], dtype=bool)

In [118]:
a==b

array([False,  True, False], dtype=bool)

In [119]:
a<=b

array([False,  True,  True], dtype=bool)

In [120]:
c = a>b

In [121]:
c

array([ True, False, False], dtype=bool)

In [122]:
c = np.array([True, False, False], bool)
any(c)

True

In [123]:
all(c)

False

Arrays can be compared to single values using broadcasting

In [124]:
a = np.array([1,3,0], float)
np.logical_and(a >0, a<3)

array([ True, False, False], dtype=bool)

In [125]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False], dtype=bool)

In [126]:
np.logical_or(a, b)

array([ True,  True,  True], dtype=bool)

Now we have the where function. The where function forms a new array from two arrays of equivalent size using a Boolean filter to choose between elements of the two. Its basic syntax is where (boolarray, truearray, falsearray):

In [128]:
a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)

/Users/michaelreinhard/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in divide
  from ipykernel import kernelapp as app


array([ 1.        ,  0.33333333,  0.        ])

**Array Item Selection and Manipulation**

We can select items from arrays using bracket notation. The nonzero function  gives a tuple of the indices fo the nonzero values in the array. The number of items in the tuple equals the number of axes of the array:

In [129]:
a = np.array([[0,1], [3, 0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

You can find whether numbers are NaN or finite: 

In [130]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([  1.,  nan,  inf])

In [131]:
np.isnan(a)

array([False,  True, False], dtype=bool)

In [132]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

**Array Item Selection and Manipulation**

In [136]:
a = np.array([[6,4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]], dtype=bool)

In [137]:
a

array([[ 6.,  4.],
       [ 5.,  9.]])

In [138]:
a[a >= 6]

array([ 6.,  9.])

In [140]:
selector = (a >= 6)
a[selector]

array([ 6.,  9.])

In [141]:
a[np.logical_and(a > 5, a < 9)]

array([ 6.])

In addition to boolean selection, it is possible to select using integer arrays. Here, the integer array contain the indicces of the elements to be taken from an array. Consider the following one-dimensional example: 

In [142]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [143]:
a[[0,0, 1, 3, 2, 1]]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [144]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
a.take(b)

array([ 1.,  1.,  4.,  4.,  1.])

Take also has an axis argument that allows us to take subsections of a given dimension.

In [145]:
a = np.array([[0,1], [2, 3]], float)
b= np.array([0,0,1], int)
a.take(b, axis=0)

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 2.,  3.]])

In [146]:
a.take(b, axis=1)

array([[ 0.,  0.,  1.],
       [ 2.,  2.,  3.]])

Opposite of the take function is the put method. It takes values from a source array and places them at specified indices in the array calling put.

put inserts the new value in and doesn't remove the old but just increases the size of the array. 

In [148]:
a = np.array([0, 1, 2, 3, 4, 5], float)
a.put([0, 3], 5)
a

array([ 5.,  1.,  2.,  5.,  4.,  5.])

**Vector and Matrix Mathematics**

In [150]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

The dot function also generates matrix multiplication.

In [153]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)

In [154]:
a

array([[ 0.,  1.],
       [ 2.,  3.]])

In [155]:
np.dot(b, a)

array([  6.,  11.])

In [156]:
np.dot(a, b)

array([  3.,  13.])

In [157]:
np.dot(a,c)

array([[  4.,   0.],
       [ 14.,   2.]])

In [158]:
np.dot(c, a)

array([[ 2.,  4.],
       [ 0.,  4.]])